version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"